# mkdocs.yml
site_name: EduManage-Documentación Técnica
site_description: Sistema integral de gestión educativa
site_author: Angel Nogueira Castaño
site_url: https://github.com/anogueira26/despr1_4_mkdocs/
# Repositorio
repo_name: anogueira26/despr1_4_mkdocs
repo_url: https://github.com/anogueira26/despr1_4_mkdocs.git
edit_uri: anogueira26/despr1_4_mkdocs/main/docs/
# Configuración del tema
theme:
 name: material
 language: es

 features:
 - navigation.tabs
 - navigation.sections
 - navigation.top
 - search.highlight
 - search.share
 - content.code.annotate
 - content.code.copy
# Plugins
plugins:
 - search:
      lang: es
 - mermaid2:
    arguments:
      theme: base
# Extensiones Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.arithmatex:
  - pymdownx.tasklist:
      custom_checkbox: true

# Navegación
nav:
  - Inicio: docs/index.md
  - Instalación: docs/instalacion.md
  - Autenticación:
      - Sistema de Login: docs/modulos/login.md
      - Configuración OAuth: docs/modulos/oauth.md
  - Dashboard:
      - Vista General: docs/modulos/dashboard.md
      - Métricas: docs/modulos/metricas.md
      - Configuración: docs/modulos/settings.md

# Configuración adicional
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anogueira26
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/tu-usuario
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML